# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-06 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ground', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playground',
            old_name='image',
            new_name='photo',
        ),
    ]
